version: "3"
services:
  app:
    container_name: kittens_container
    image: nadiyaka/kittens_image
    ports:
      - 1234:1234
    command: ["bundle", "exec", "rackup", "--host", "0.0.0.0", "-p", "1234"]
    environment:
      RACK_ENV: ${RACK_ENV}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@DB:5432/${POSTGRES_DB}
    depends_on:
      - db
  db:
    container_name: DB
    image: postgres:10.13-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
